/**
 * Ticker → primary company domain, used only as a fallback source for
 * apps/indexer/src/logos.ts's favicon-service lookup when Robinhood's own
 * rhj/assets logoUrl doesn't pan out (see that file's header comment for
 * why that happens more often than expected).
 *
 * Deliberately incomplete: a wrong domain risks serving a real but WRONG
 * company's logo, which is worse than the honest monogram fallback a
 * missing entry gets instead — so this only lists tickers whose domain is
 * unambiguous. Small/micro-cap or recently-listed names without an
 * obviously-correct domain (e.g. tickers P, AAOI, USAR, NU as of
 * 2026-07-24) are intentionally left out rather than guessed.
 */
export const COMPANY_DOMAINS: Record<string, string> = {
  AAPL: 'apple.com',
  AMAT: 'appliedmaterials.com',
  AMD: 'amd.com',
  AMZN: 'amazon.com',
  APLD: 'applieddigital.com',
  ASML: 'asml.com',
  ASTS: 'ast-science.com',
  AVGO: 'broadcom.com',
  BA: 'boeing.com',
  BABA: 'alibaba.com',
  BE: 'bloomenergy.com',
  CCL: 'carnival.com',
  CLSK: 'cleanspark.com',
  COIN: 'coinbase.com',
  COST: 'costco.com',
  CRCL: 'circle.com',
  CRWD: 'crowdstrike.com',
  CRWV: 'coreweave.com',
  DDOG: 'datadoghq.com',
  DELL: 'dell.com',
  ELF: 'elfcosmetics.com',
  EWY: 'ishares.com',
  F: 'ford.com',
  FUTU: 'futuholdings.com',
  GLW: 'corning.com',
  GME: 'gamestop.com',
  GOOGL: 'google.com',
  INTC: 'intel.com',
  INTU: 'intuit.com',
  IONQ: 'ionq.com',
  LLY: 'lilly.com',
  LULU: 'lululemon.com',
  MDB: 'mongodb.com',
  META: 'meta.com',
  MRVL: 'marvell.com',
  MSFT: 'microsoft.com',
  MSTR: 'strategy.com',
  MU: 'micron.com',
  MXL: 'maxlinear.com',
  NFLX: 'netflix.com',
  NOW: 'servicenow.com',
  NVDA: 'nvidia.com',
  ORCL: 'oracle.com',
  PLTR: 'palantir.com',
  QCOM: 'qualcomm.com',
  QQQ: 'invesco.com',
  RBLX: 'roblox.com',
  RDDT: 'reddit.com',
  RGTI: 'rigetti.com',
  RIVN: 'rivian.com',
  SGOV: 'ishares.com',
  SHOP: 'shopify.com',
  SLV: 'ishares.com',
  SMCI: 'supermicro.com',
  SNDK: 'sandisk.com',
  SOFI: 'sofi.com',
  SOXX: 'ishares.com',
  SPCX: 'spacex.com',
  SPMO: 'invesco.com',
  SPY: 'ssga.com',
  TSLA: 'tesla.com',
  TSM: 'tsmc.com',
  TTWO: 'take2games.com',
  UPS: 'ups.com',
  USO: 'uscfinvestments.com',
  WDAY: 'workday.com',
  XLK: 'ssga.com',
  XOM: 'exxonmobil.com',
  ZM: 'zoom.us',
  ZS: 'zscaler.com',
};
